points:
  # When to award points for items. One of:
  # - AUTO_DEPOSIT_ALL:
  #   All items a player picks up are automatically moved into their ItemRace inventory which they cannot take items out of.
  # - AUTO_DEPOSIT:
  #   Similar to AUTO_DEPOSIT_ALL but only items which the player can earn points for will be deposited.
  #   This is only really useful if a denylist has been created
  # - DEPOSIT_COMMAND:
  #   Similar to AUTO_DEPOSIT, but players choose which items to move to their ItemRace inventory using `/itemrace deposit`.
  #   If no arguments are specified, the item in the player's hand is deposited.
  # - DEPOSIT_GUI:
  #   Similar to DEPOSIT_COMMAND except, if no arguments are specified, then an inventory GUI is opened.
  #   Players can move any items they wish to deposit into that inventory.
  # - MAX_INVENTORY:
  #   Similar to AUTO_DEPOSIT, but players do not lose deposited items. Instead, their ItemRace inventory is based on the
  #   maximum amount of a given item they have held in their inventory at any time.
  # - INVENTORY:
  #   Players are scored based on the items currently in their inventory.
  # - ENDER_CHEST:
  #   Similar to INVENTORY, but also includes items in their ender chest.
  # NOTE: Currently, INVENTORY and ENDER_CHEST do not support any live updates (e.g: scoreboard, and in GUIs) and only work for players who are currently online!
  award_mode: DEPOSIT_GUI

  # The rate at which the number of items needed to get each point increases (positive integer)
  # This is done exponentially such that (assuming `award_point_for_first_item` is `true`):
  # - If this is 1, players will get 1 point for every item deposited
  # - If this is 2, players will still get a point for the first and second item they deposit,
  #   but won't get their third point until their 4th item, then until their 8th item
  # - If this is 3, players will get a point for their 1st, 3rd, 9th, 27th... item
  items_per_point_growth_rate: 2

  # Whether to award a point for the first item a player deposits (true/false)
  # If this is false, players won't receive their first point until they deposit `items_per_point_growth_rate` items.
  # This has no effect if `items_per_point_growth_rate` is 1.
  award_for_first_item: true

  # The maximum number of points a player can be awarded for a single type of item (integer)
  # If this is negative, an unlimited number of points may be awarded.
  # If `points.award_mode` is `DEPOSIT_COMMAND` or `DEPOSIT_INVENTORY`
  #  players will be prevented from depositing more items than they can be awarded points for.
  max_per_item_type: -1


# These options have no effect if `points.award_mode` is `INVENTORY` or `ENDER_CHEST`
deposited_items:
  # Whether deposited items should persist between server restarts (true/false)
  # If this is true, deposited items will be saved to a file alongside this config when the server shuts down
  persist: true

  # How often, in minutes, deposited items should be auto-saved (number)
  # This has no effect if `persist` is `false`
  # If this is 0, deposited items will only be saved when the plugin is disabled (e.g.: when the server shuts down)
  autosave_frequency: 5

  gui:
    # Whether to:
    # - split an item type into multiple ordinary stacks (true)
    # - combine them into one large stack, showing as up to 99 items (false)
    split_into_stacks: false


# NOTE: Currently, the scoreboard does not work if `points.award_mode is `INVENTORY` OR `ENDER_CHEST`
scoreboard:
  # Whether the scoreboard is toggled on by default (on/off)
  # Players can toggle this on and off for themselves using `/itemrace togglescoreboard`
  default_state: on

  # Where scores should be displayed (SIDEBAR/PLAYER_LIST/BELOW_NAME)
  display_slot: SIDEBAR


denylist:
  # Items which players cannot deposit.
  # For a list of item names, see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  # You do not need to specify air-like items!
  items:
  #- COBBLESTONE
  #- OAK_LEAVES

  # Set this to true if there is only a limited number of items you want to allow players to deposit.
  treat_as_allowlist: false

  # Whether damaged tools should count towards the total number of each tool a player has deposited (true/false)
  # If this is false, players will not be able to deposit damaged tools in `DEPOSIT_COMMAND` or `DEPOSIT_INVENTORY` mode.
  # If this is false, damaged tools will still be removed from players' inventories in AUTO_DEPOSIT_ALL mode
  #   but won't be added to their ItemRace inventory.
  allow_damaged_tools: true